{% set version = "0.3.0" %}
{% set build = 0 %}

package:
  name: fabmos
  version: {{ version }}

source:
  #git_url: https://github.com/BoldingBruggeman/fabmos.git
  url: https://github.com/BoldingBruggeman/fabmos/releases/download/v{{ version }}/fabmos.tar.gz
  sha256: d81e0d37ad35052b22456123754c5bf0e7f54007adaeb467283108b73b55e71d

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make                                   # [not win]
    - {{ compiler('fortran') }}              # [not win]
    - {{ stdlib("c") }}                      # [not win] on Windows this pulls in VS and causes cmake to use its cl.exe, which is incompatible with the m2w64 version of windres.exe
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ stdlib("m2w64_c") }}                # [win]
  host:
    - python {{ python }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - xarray
    - mpi4py
    - netCDF4
    - pygetm >=0.9.2
    - scipy
    - h5py
    - m2w64-gcc-libgfortran      # [win] NB m2w64-gcc-libs and m2w64-gcc-libs-core are added automatically by m2w64 compiler functions under build

test:
  imports:
    - fabmos

about:
  home: https://github.com/BoldingBruggeman/fabmos
  summary: 'FABM offline simulator'
  description: |
    Offline simulator for the Framework for Aquatic Biogeochemical Models
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
