{% set version = "0.3.3" %}
{% set build = 0 %}

package:
  name: fabmos
  version: {{ version }}

source:
  #git_url: https://github.com/BoldingBruggeman/fabmos.git
  url: https://github.com/BoldingBruggeman/fabmos/releases/download/v{{ version }}/fabmos.tar.gz
  sha256: 60477f8e9daf73421460b05ae15ffeb4b268bd0eb9b623a6906d8f6161821120

build:
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('fortran') }}              # [not win]
    - {{ stdlib("c") }}                      # [not win] on Windows this pulls in VS and causes cmake to use its cl.exe, which is incompatible with the m2w64 version of windres.exe
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ stdlib("m2w64_c") }}                # [win]
  host:
    - python {{ python }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - xarray
    - mpi4py
    - netCDF4
    - pygetm >=0.9.12
    - scipy
    - h5py

test:
  imports:
    - fabmos

about:
  home: https://github.com/BoldingBruggeman/fabmos
  summary: 'FABM offline simulator'
  description: |
    Offline simulator for the Framework for Aquatic Biogeochemical Models
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/BoldingBruggeman/fabmos/wiki

extra:
  recipe-maintainers:
    - jornbr
